-- Ejecutar en el SQL Editor de un PROYECTO SUPABASE NUEVO exclusivo para CIMARI.
create table if not exists public.cimari_maintenance_records (
 id bigint generated by default as identity primary key, polygon_id text not null,
 polygon_name text, turno integer, work_date date, work_time time, day_name text,
 status text default 'PENDIENTE', pct integer default 0 check (pct between 0 and 100),
 elaboro text, reviso text, activity text, observations text, photo_type text,
 photos jsonb default '[]'::jsonb, created_at timestamptz default now()
);
alter table public.cimari_maintenance_records enable row level security;
grant select,insert,update,delete on public.cimari_maintenance_records to anon;
grant usage,select on sequence public.cimari_maintenance_records_id_seq to anon;
drop policy if exists "cimari read records" on public.cimari_maintenance_records;
drop policy if exists "cimari insert records" on public.cimari_maintenance_records;
drop policy if exists "cimari update records" on public.cimari_maintenance_records;
drop policy if exists "cimari delete records" on public.cimari_maintenance_records;
create policy "cimari read records" on public.cimari_maintenance_records for select to anon using (true);
create policy "cimari insert records" on public.cimari_maintenance_records for insert to anon with check (true);
create policy "cimari update records" on public.cimari_maintenance_records for update to anon using (true) with check (true);
create policy "cimari delete records" on public.cimari_maintenance_records for delete to anon using (true);
insert into storage.buckets(id,name,public) values('cimari-evidencias','cimari-evidencias',true) on conflict(id) do update set public=true;
drop policy if exists "cimari read photos" on storage.objects;
drop policy if exists "cimari upload photos" on storage.objects;
create policy "cimari read photos" on storage.objects for select to anon using(bucket_id='cimari-evidencias');
create policy "cimari upload photos" on storage.objects for insert to anon with check(bucket_id='cimari-evidencias');
